services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    ports:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: